### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by stevie6410** [TechDevsSoftware/service-centre#7]
Add real testimonials or take the module out

**Comment by stevie6410** [comment]
@adamfox999  Do we want this, none of it works as is?

<img width="1280" alt="screen shot 2018-04-07 at 21 40 05" src="https://user-images.githubusercontent.com/1828544/38460144-4c01512c-3aac-11e8-9a66-91250a0979b9.png">

**Comment by adamfox999** [comment]
Done
